export default {
    welcome: "ようこそ！",
    play: "ゲーム開始",
    settings: "設定",
    stars: "賭けるスター数:",
    star_number: "スター数:",
    chi: 'チー',
    pon: 'ポン',
    kan: 'カン',
    ron: 'ロン',
    tsumo: 'ツモ',
    skip: 'スキップ',
    setting: 'ゲーム設定',
    language: '言語:',
    savesetting: '保存',
  };